### ISSUE TITLE
deprecation message

### ISSUE THREAD

**Issue by sc00ter** [TamaMcGlinn/nvim-lspconfig-ada#1]
calling the setup code now results in a als deprecation message:
require("lspconfig").als.setup{
  on_attach = on_attach,
  capabilities = capabilities,
  on_init = require("gpr_selector").als_on_init
}

**Comment by TamaMcGlinn** [comment]
Yes, that is expected. Switch from [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/) to [TamaMcGlinn/nvim-lspconfig](https://github.com/TamaMcGlinn/nvim-lspconfig/) to fix it for now. The removal of the faulty als inside neovim/nvim-lspconfig will be done for version 0.2, so after that release you can switch back again. In the meantime, users of default neovim/nvim-lspconfig will see this message, have [issue 1683](https://github.com/neovim/nvim-lspconfig/issues/1683), not being able to jump to references. They do not want to remove lsp servers without first deprecating, but I agree this is confusing, it's just out of my control.

**Comment by TamaMcGlinn** [comment]
So, this has been fixed but the nvim-lspconfig owners [have just proposed to break this again](https://github.com/neovim/nvim-lspconfig/pull/3310#issuecomment-2414304341). Hang tight, this will likely be reopened soon.
