### ISSUE TITLE
Change in server_configurations breaks lsp config with Mason

### ISSUE THREAD

**Issue by edwardgallyot** [TamaMcGlinn/nvim-lspconfig-ada#3]
Commit #2 breaks my setup when I have als installed with Mason. Right now I can pin to the previous commit using Lazy.nvim but it'd be good in future to copy (or symlink) this on install instead of renaming it.

**Comment by TamaMcGlinn** [comment]
Do you have repro steps? I also have als installed with mason, so I don't understand how this "breaks your setup".

**Comment by edwardgallyot** [comment]
I updated to the latest commit using lazy.nvim and lspconfig cannot find als in server_configurations.md

Apologies, "breaks my setup" is incredibly vague. Let me know which logs and configs it would be helpful to send.

**Comment by TamaMcGlinn** [comment]
did you update nvim-lspconfig to the latest as well? They made a breaking change for us, so either both need to be up to date or neither.

**Comment by edwardgallyot** [comment]
Ah I'm sorry I was using your fork of nvim-lspconfig. I had got the impression that I needed it after reading [https://github.com/neovim/nvim-lspconfig/issues/1683](this), but this works after updating to the latest on both nvim-lspconfig and this repo using Lazy.nvim. Thanks for you help!

**Comment by TamaMcGlinn** [comment]
Ah, thanks for pointing that out. I'll delete my fork to avoid the confusion for others.
